[versions]
compose = "1.1.1"
coroutines = "1.6.0"
espresso = "3.4.0"
gradleplugin = "7.1.3"
hilt = "2.41"
kotlin = "1.6.10"
lifecycle = "2.4.1"
okhttp = "4.9.3"
retrofit = "2.9.0"
room = "2.4.2"
navigation = "2.5.0-rc01"

[libraries]
android-appCompat = "androidx.appcompat:appcompat:1.4.1"
android-coreKtx = "androidx.core:core-ktx:1.7.0"
android-hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
android-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
android-hilt-compose = "androidx.hilt:hilt-navigation-compose:1.0.0"
android-hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
android-material = "com.google.android.material:material:1.5.0"
android-test-compose = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
android-test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
android-test-idling = { module = "androidx.test.espresso:espresso-idling-resource", version.ref = "espresso" }
android-test-junit4 = "androidx.test.ext:junit:1.1.3"
coil-compose = "io.coil-kt:coil-compose:2.0.0-rc03"
compose-activity = "androidx.activity:activity-compose:1.4.0"
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-materialIcons = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-runtimeLivedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
gson-gson = "com.google.code.gson:gson:2.9.0"
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
lifecycle-livedataKtx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-runtimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lottie-compose = "com.airbnb.android:lottie-compose:5.0.3"
okhttp-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
paging-common = "androidx.paging:paging-common-ktx:3.1.1"
paging-compose = "androidx.paging:paging-compose:1.0.0-alpha14"
result-jvm = "com.github.kittinunf.result:result-jvm:5.2.1"
retrofit-gsonConverter = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }


[bundles]
compose = ["coil-compose", "compose-activity", "compose-material", "compose-materialIcons", "compose-runtimeLivedata", "compose-ui", "compose-ui-tooling", "compose-ui-tooling-preview", "paging-compose"]
lifecycle = ["lifecycle-livedataKtx", "lifecycle-runtimeKtx", "lifecycle-viewmodel-compose"]
networking = ["gson-gson", "okhttp-interceptor", "retrofit-gsonConverter", "retrofit-retrofit"]
room = ["room-ktx", "room-paging", "room-runtime"]
navigation = ["navigation-fragment-ktx","navigation-ui-ktx"]

[plugins]
android-application = { id = "com.android.application", version.ref = "gradleplugin" }
android-library = { id = "com.android.library", version.ref = "gradleplugin" }
detekt = "io.gitlab.arturbosch.detekt:1.19.0"
hilt-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
spotless = "com.diffplug.spotless:6.4.2"
toml-checker = "com.github.ben-manes.versions:0.42.0"
toml-updater = "nl.littlerobots.version-catalog-update:0.3.1"