name: Android CI

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.6
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: SonarQube Quality Gate Check
      uses: SonarSource/sonarqube-quality-gate-action@v1.0.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Unit Test
      run: ./gradlew testDebugUnitTest
    - name: Android Test Report Action
      uses: asadmansr/android-test-report-action@v1.2.0
    - name: Build Release Bundle
      run: ./gradlew bundle
    - uses: r0adkll/sign-android-release@v1
      name: Sign Bundle
      id: sign_app
      with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
    - name: Upload Bundle
      uses: actions/upload-artifact@v2
      with:
          name: release.aab
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
