name: Android CI

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [23, 25, 27, 29, 31, 33]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Gradle cache
      uses: gradle/gradle-build-action@v2
    - name: AVD cache
      uses: actions/cache@v3
      id: avd-cache
      with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}   
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: create AVD and generate snapshot for caching
      if: steps.avd-cache.outputs.cache-hit != 'true'
      uses: reactivecircus/android-emulator-runner@v2
      with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."    
    - name: Android Emulator
      uses: ReactiveCircus/android-emulator-runner@v2.26.0
      with:
          api-level: ${{ matrix.api-level }}      
          script: ./gradlew connectedCheck
    - name: Unit Test
      run: ./gradlew jacocoTestReport
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Gradle packages
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Build and analyze
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./gradlew build sonarqube --info
    - name: Android Test Report Action
      uses: asadmansr/android-test-report-action@v1.2.0
    - name: Build Release Bundle
      run: ./gradlew bundle
    - uses: r0adkll/sign-android-release@v1
      name: Sign Bundle
      id: sign_app
      with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
    - name: Upload Bundle
      uses: actions/upload-artifact@v2
      with:
          name: release.aab
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
